### ISSUE TITLE
使用升级功能，APK下载完成报错，怎么解决

### ISSUE THREAD

**Issue by soedev** [781238222/flutter-do#1]
`E/flutter ( 9305): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference, null)
E/flutter ( 9305): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 9305): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 9305): <asynchronous suspension>
E/flutter ( 9305): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 9305): #3      FlutterUpgrade.installAppForAndroid (package:flutter_upgrade/src/flutter_upgrade.dart:33:27)
E/flutter ( 9305): #4      _SimpleAppUpgradeWidget._downloadApk.<anonymous closure> (package:flutter_upgrade/src/simple_app_upgrade.dart:323:26)
E/flutter ( 9305): #5      DioForNative.download.<anonymous closure>.<anonymous closure> (package:dio/src/entry/dio_for_native.dart:164:30)
E/flutter ( 9305): #6      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 9305): #7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 9305): #8      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
E/flutter ( 9305): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 9305): #10     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 9305): #11     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 9305): #12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter ( 9305): #13     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 9305): #14     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 9305): #15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 9305): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 9305): #17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 9305): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 9305): `

**Comment by 781238222** [comment]
能不能提供下手机型号和系统版本

**Comment by soedev** [comment]
问题解决了， 
![image](https://user-images.githubusercontent.com/40556697/78734573-2bbd8380-797b-11ea-8144-bb04dc14402a.png)  这里没有根据Manifest 设置里的来
