### ISSUE TITLE
flutter_app_upgrade 1.0.1以后报错

### ISSUE THREAD

**Issue by mrTangYun** [781238222/flutter-do#12]
android\src\main\kotlin\com\flutter\flutter_app_upgrade\FlutterAppUpgradePlugin.kt: (24, 14): Redeclaration: FlutterAppUpgradePlugin
1.0.0是好的

**Comment by mrTangYun** [comment]
clean以后又报这个错
flutter_app_upgrade-1.0.2\android\src\main\kotlin\com\flutter\flutter_app_upgrade\FlutterAppUpgradePlugin.kt: (10, 28): Unresolved reference: NonNull

**Comment by 781238222** [comment]
如果你用过1.0.2以前的版本，需要收到把以前的版本删除，然后重新get

**Comment by mrTangYun** [comment]
是的，删除老版本后解决，谢谢
