### ISSUE TITLE
使用过程中的几个问题，建议优化

### ISSUE THREAD

**Issue by xie438305665** [781238222/flutter-do#14]
1.下载完成 应该主动 关闭dialog, 而不是一直存在
2.下载完成，失败，建议暴露回调，以方便更多的逻辑操作
3.如果直接apk跳转到安装界面，这个时候取消安装返回。dialog一直存在，除非杀掉APP

**Comment by 781238222** [comment]
非常感谢您的建议，会尽快优化。

**Comment by 781238222** [comment]
1.1.0版本全部优化
