### ISSUE TITLE
Android 强制升级， 点击物理返回键可以让 Dialog 消失， 怎么能不让他消失呢

### ISSUE THREAD

**Issue by Antduo** [781238222/flutter-do#18]
Android 强制升级， 点击物理返回键可以让 Dialog 消失， 怎么能不让他消失呢

**Comment by 781238222** [comment]
使用WillPopScope 拦截处理，具体用法查看：http://laomengit.com/flutter/widgets/WillPopScope.html

**Comment by 781238222** [comment]
1.10版本已经添加此功能
