### ISSUE TITLE
Flutter_app_upgrade 集成后IOS上架会被拒绝,慎重

### ISSUE THREAD

**Issue by voidJeffrey** [781238222/flutter-do#30]
As we discussed, your app was found to be out of compliance with App Store Review Guidelines 2.3.1 and 2.5.2.

Specifically, we continue to find remote updating and upgrading functionality in this app via Flutter. It would be appropriate to remove any and all remote updating functionality from your app, such as your app’s Flutter_app_upgrade.framework before resubmitting for review.

Apple 回复的

**Comment by 781238222** [comment]
iOS app是不允许在App内弹出升级提示的（即使是原生也不允许），
所以你们要自己做出规避，查查别的应用是如何处理App内弹出升级提示的。
