### ISSUE TITLE
No implementation found for method getAppInfo on channel flutter_app_upgrade

### ISSUE THREAD

**Issue by d1bug** [781238222/flutter-do#5]
插件都按照要求安装好了，可是运行都时候报错：
No implementation found for method getAppInfo on channel flutter_app_upgrade

**Comment by d1bug** [comment]
companion object {
    lateinit var mContext: Context

    @JvmStatic
    fun registerWith(registrar: Registrar) {
      this.mContext = registrar.activity()
      val channel = MethodChannel(registrar.messenger(), "flutter_upgrade")
      channel.setMethodCallHandler(FlutterAppUpgradePlugin())
    }

  }


flutter_upgrade-------》flutter_app_upgrade

**Comment by 781238222** [comment]
感谢您的反馈，已经修复此bug
